import React, { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'pt' | 'en';

interface Translations {
  [key: string]: {
    [key: string]: string;
  };
}

const translations: Translations = {
  pt: {
    login_title: "Acesse sua conta",
    email_label: "E-MAIL",
    password_label: "SENHA",
    login_button: "ENTRAR AGORA",
    login_success: "Login bem-sucedido!",
    invalid_credentials: "Credenciais inválidas.",
    topic_label: "Digite a ideia do seu vídeo com o máximo de detalhes possíveis:",
    topic_placeholder: "Escreva ou cole o seu prompt aqui ...",
    generate_button: "Gerar Vídeo",
    generating: "Gerando...",
    success_toast: "Ideia de vídeo viral gerada com sucesso!",
    error_toast: "Por favor, insira um tópico para gerar a ideia.",
    idea_title: "Sua Ideia Viral:",
    checking_credentials: "Verificando credenciais...",
    forgot_password: "Esqueceu sua senha?",
    niche_tab: "Nicho",
    duration_tab: "Duração",
    advanced_tab: "Avançado",
    select_niche: "Selecione seu nicho",
    selected: "Selecionado",
    video_duration: "Duração do Vídeo",
    duration_slider_label: "Ajuste a duração (segundos)",
    advanced_features: "Recursos Avançados",
    engagement_boost: "Boost de Engajamento",
    engagement_boost_desc: "Crie micro-cenas em períodos estratégicos que irão manter sua retenção acima de 87%",
    trending_algorithm: "Algoritmo de Retenção", 
    trending_algorithm_desc: "Adicione thumbnail de acordo com o nicho escolhido que estão em tendência atual fazendo com que seu CTR fique altíssimo", 
    trend_analysis: "Análise de Tendência", 
    trend_analysis_desc: "O sistema constantemente irá procurar na base de dados mundiais vídeos do mesmo nicho do seu com potencial de viralização e irá te avisar para que você adapte o estilo no próximo vídeo", 
    viral_hook: "Gancho Viral",
    viral_hook_desc: "Busque por trechos virais de vídeos que estão em alta no mundo e recrie essas cenas no seu vídeo.",
    persistence_mode: "Modo Persistência",
    persistence_mode_desc: "A IA analisa periodicamente o vídeo postado e refaz correções necessárias para garantir máxima performance.",
    ai_remodel_tab: "Remodelagem IA",
    long_videos: "Vídeos longos",
    long_duration_label: "1 min até 60 min",
    processing: "Processando...",
    remodel_video_ai: "Remodelar Vídeo com IA",
    remodel_result_title: "Resultado da Remodelagem",
    copy_result: "Copiar Resultado",
    paste_youtube_link: "Cole o link do Youtube",
    paste_tiktok_link: "Cole o link do Tiktok",
    paste_facebook_link: "Cole o link do Facebook",
    paste_instagram_link: "Cole o link do Instagram",
    enter_valid_url: "Por favor, insira uma URL válida do",
    // Niche Labels
    niche_ai_tech: "AI & Tecnologia",
    niche_finance: "Finanças",
    niche_storytelling: "Contação de Histórias",
    niche_true_crime: "True Crime",
    niche_gaming: "Gaming",
    niche_cartoon: "Desenho Animado",
    niche_3d_animation: "Animações em 3D",
    niche_superheroes: "Super Heróis",
    niche_babies: "Bebês",
    niche_pets: "Pets & Animais",
    niche_food: "Comida / Receitas",
    niche_lifestyle: "Lifestyle",
    niche_personal_dev: "Desenvolvimento Pessoal",
    niche_education: "Educação Curta",
    niche_curiosities: "Curiosidades",
    niche_diy: "DIY / Hacks",
    niche_health: "Saúde & Fitness",
    niche_fashion: "Moda & Beleza",
    niche_relationships: "Relacionamentos",
    niche_humor: "Humor / Memes",
    niche_podcasts: "Podcasts em cortes",
    niche_asmr: "ASMR",
    niche_travel: "Viagens",
    niche_business: "Negócios Online",
    // Activation Popup & Plan Page
    activate_premium_title: "ATIVE SUA CONTA PREMIUM",
    activate_premium_subtitle: "Desbloqueie o poder total da IA para criar vídeos virais ilimitados!",
    discount_percentage: "% DE DESCONTO",
    what_you_get: "O que você recebe:",
    unlimited_access_title: "Acesso Ilimitado",
    unlimited_access_desc: "Gere quantos vídeos quiser sem restrições",
    viral_videos_seconds_title: "Vídeos Virais em Poucos Minutos",
    viral_videos_seconds_desc: "Crie vídeos virais em poucos minutos com a IA mais avançada do mundo atualmente",
    premium_functions_title: "Funções Premium",
    premium_functions_desc: "Tenha acesso a ferramentas exclusivas da makeitviral que farão seu vídeo viralizar rapidamente após a postagem",
    updates_title: "Atualizações",
    updates_desc: "Atualizações grátis durante 1 ano",
    exclusive_group_title: "Grupo Exclusivo",
    exclusive_group_desc: "Grupo de networking exclusivo para assinantes da makeitviral",
    subscribe_now: "ASSINAR AGORA",
    secure_pix_payment: "Pagamento 100% SEGURO via Pix",
    account_needs_activation_title: "Sua conta precisa ser ativada",
    account_needs_activation_desc: "Ative por 1 ano de uso ilimitado por",
    generating_pix: "Processando Pagamento...",
    pix_error: "Erro ao gerar código PIX. Tente novamente.",
    try_again: "Tentar novamente",
    expires_in: "EXPIRA EM:",
    copied: "COPIADO!",
    copy_pix_code: "COPIAR CÓDIGO PIX",
    best_option: "MELHOR OPÇÃO",
    last_day: "ÚLTIMO DIA",
    apply: "APLICAR",
    coupon_placeholder: "Cupom de Desconto",
    secure_environment: "PAGAMENTO SEGURO",
    guarantee: "GARANTIA DE 7 DIAS",
    coupon_applied: "Cupom aplicado com sucesso!",
    invalid_coupon: "Cupom inválido.",
    coupons_remaining: "4 cupons restantes",
    // Credit Card Payment Keys
    cc_payment_title: "Pagamento com Cartão de Crédito",
    cc_payment_subtitle: "Insira os detalhes do seu cartão de crédito para completar o pagamento de",
    cc_card_number: "Número do Cartão",
    cc_card_name: "Nome do Titular",
    cc_expiry: "Validade (MM/AA)",
    cc_cvv: "CVV",
    pay_now: "PAGAR AGORA",
    subscription: "ASSINATURA",
    // Watermark Keys
    include_watermark: "Incluir Marca D'água?",
    channel_name_label: "Nome do Canal/Usuário",
    channel_name_placeholder: "@seu_canal_aqui",
    // New Annual Plan Keys
    annual_plan_only: "Disponível apenas no Plano Anual",
    annual_plan_label: "Plano Anual",
    new_tag: "Novidade",
  },
  en: {
    login_title: "Access your account",
    email_label: "EMAIL",
    password_label: "PASSWORD",
    login_button: "LOGIN NOW",
    login_success: "Login successful!",
    invalid_credentials: "Invalid credentials.",
    topic_label: "Enter your video idea with as much detail as possible:",
    topic_placeholder: "Write or paste your prompt here...",
    generate_button: "Generate Video",
    generating: "Generating...",
    success_toast: "Viral video idea generated successfully!",
    error_toast: "Please enter a topic to generate an idea.",
    idea_title: "Your Viral Idea:",
    checking_credentials: "Verifying credentials...",
    forgot_password: "Forgot your password?",
    niche_tab: "Niche",
    duration_tab: "Duration",
    advanced_tab: "Advanced",
    select_niche: "Select your niche",
    selected: "Selected",
    video_duration: "Video Duration",
    duration_slider_label: "Adjust duration (seconds)",
    advanced_features: "Advanced Features",
    engagement_boost: "Engagement Boost",
    engagement_boost_desc: "Create micro-scenes at strategic intervals to keep your retention above 87%",
    trending_algorithm: "Retention Algorithm", 
    trending_algorithm_desc: "Add niche-specific thumbnail that are currently trending to skyrocket your CTR", 
    trend_analysis: "Trend Analysis", 
    trend_analysis_desc: "The system will constantly search global databases for videos in your niche with viral potential and notify you so you can adapt the style in your next video", 
    viral_hook: "Viral Hook",
    viral_hook_desc: "Search for trending viral video clips and recreate those scenes to make your video irresistible.",
    persistence_mode: "Persistence Mode",
    persistence_mode_desc: "AI periodically analyzes the posted video and makes necessary corrections to ensure maximum performance.",
    ai_remodel_tab: "AI Remodel",
    long_videos: "Long Videos",
    long_duration_label: "1 min up to 60 min",
    processing: "Processing...",
    remodel_video_ai: "Remodel Video with AI",
    remodel_result_title: "Remodeling Result",
    copy_result: "Copy Result",
    paste_youtube_link: "Paste YouTube link",
    paste_tiktok_link: "Paste TikTok link",
    paste_facebook_link: "Paste Facebook link",
    paste_instagram_link: "Paste Instagram link",
    enter_valid_url: "Please enter a valid URL from",
    // Niche Labels
    niche_ai_tech: "AI & Technology",
    niche_finance: "Finance",
    niche_storytelling: "Storytelling",
    niche_true_crime: "True Crime",
    niche_gaming: "Gaming",
    niche_cartoon: "Cartoon",
    niche_3d_animation: "3D Animation",
    niche_superheroes: "Superheroes",
    niche_babies: "Babies",
    niche_pets: "Pets & Animals",
    niche_food: "Food & Recipes",
    niche_lifestyle: "Lifestyle",
    niche_personal_dev: "Personal Growth",
    niche_education: "Education",
    niche_curiosities: "Trivia / Fun Facts",
    niche_diy: "DIY / Life Hacks",
    niche_health: "Health & Fitness",
    niche_fashion: "Fashion & Beauty",
    niche_relationships: "Relationships",
    niche_humor: "Humor / Memes",
    niche_podcasts: "Podcast Clips",
    niche_asmr: "ASMR",
    niche_travel: "Travel",
    niche_business: "Online Business",
    // Activation Popup & Plan Page
    activate_premium_title: "ACTIVATE PREMIUM ACCOUNT",
    activate_premium_subtitle: "Unlock the total power of AI to create unlimited viral videos!",
    discount_percentage: "% OFF",
    what_you_get: "What you receive:",
    unlimited_access_title: "Unlimited Access",
    unlimited_access_desc: "Generate as many videos as you want without any restrictions",
    viral_videos_seconds_title: "Viral Videos in Seconds",
    viral_videos_seconds_desc: "Create viral content in seconds with the world's most advanced AI",
    premium_functions_title: "Premium Features",
    premium_functions_desc: "Get exclusive access to makeitviral tools that boost your video engagement instantly",
    updates_title: "Updates",
    updates_desc: "Free updates for 1 full year",
    exclusive_group_title: "Exclusive Group",
    exclusive_group_desc: "Access our exclusive networking group for makeitviral subscribers",
    subscribe_now: "SUBSCRIBE NOW",
    secure_pix_payment: "100% SECURE PAYMENT", 
    account_needs_activation_title: "Account Activation Required",
    account_needs_activation_desc: "Activate for 1 year of unlimited use for",
    generating_pix: "Processing Payment...",
    pix_error: "Error generating payment. Please try again.",
    try_again: "Try again",
    expires_in: "EXPIRES IN:",
    copied: "COPIED!",
    copy_pix_code: "COPY CODE",
    best_option: "BEST VALUE",
    last_day: "LAST DAY",
    apply: "APPLY",
    coupon_placeholder: "Discount Coupon",
    secure_environment: "SECURE ENVIRONMENT",
    guarantee: "7-DAY GUARANTEE",
    coupon_applied: "Coupon applied successfully!",
    invalid_coupon: "Invalid coupon.",
    coupons_remaining: "4 coupons remaining",
    // Credit Card Payment Keys
    cc_payment_title: "Credit Card Payment",
    cc_payment_subtitle: "Enter your credit card details to complete the payment of",
    cc_card_number: "Card Number",
    cc_card_name: "Card Holder Name",
    cc_expiry: "Expiry (MM/YY)",
    cc_cvv: "CVV",
    pay_now: "PAY NOW",
    subscription: "SUBSCRIPTION",
    // Watermark Keys
    include_watermark: "Include Watermark?",
    channel_name_label: "Channel/User Name",
    channel_name_placeholder: "@your_channel_here",
    // New Annual Plan Keys
    annual_plan_only: "Available only on Annual Plan",
    annual_plan_label: "Annual Plan",
    new_tag: "New",
  }
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('en');
  
  const t = (key: string) => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) throw new Error('useLanguage must be used within a LanguageProvider');
  return context;
};